### PR TITLE
Pass puppet_module to ERB

### PR DESCRIPTION
**Pull request by raphink**
This allows to access the module name using
the @module variable.

### CODE REVIEW

**Comment by raphink** [comment]
@cmurphy this PR would be very useful to generate docs for example (with links to issues URL, etc.).

**Comment by cmurphy** [comment]
@raphink instead of adding a new instance variable to the template, could :puppet_module be added as a key in the file_configs variable? Then it would be wrapped in the @configs variable.

**Comment by raphink** [comment]
@cmurphy I wanted to avoid that as that might conflict with existing parameters in @configs.

**Comment by cmurphy** [comment]
@raphink if there's already a :puppet_module key in @configs then the user wouldn't make use of the @module variable anyway.

**Comment by raphink** [comment]
Updated the commit. Do you like this better @cmurphy ?

**Comment by cmurphy** [comment]
:+1:  thanks!

**Comment by raphink** [comment]
@cmurphy thanks. Could you cut a new release, please?

**Comment by cmurphy** [comment]
@raphink yes, will do this week.

**Pull request merged**
